bnb/awesome-developer-streams

README.md

Add noopkat to Developers That Stream

---

README.md

Add Feross Aboukhadijeh to Developers That Stream

---

README.md

Add @thlorenz to Developers That Stream

Add thlorenz to Developers That Stream

---

README.md

Add Shirley Wu to README.md

---

README.md

Adds @kyleshevlin to the list! ⚛

Add Kyle Shevlin to README.md

---

README.md

Adds @thelarkinn to the list! 📦

Add Sean Larkin to README.md

---

README.md

Add Brian Clark to README.md

---

README.md

Adds @yoshuawuyts to the list! 🚂

Add Yosh to README.md

---

README.md

I'm just getting started, so maybe I don't fit into an awesome list yet, but maybe?

Add Russell Hay to README.md

---

README.md

Adds myself (Collin Henderson aka syropian) to the list. Thanks for making this!

Adds Collin Henderson to list

---

README.md

Adds Tierney Cyren to the list 🎉

Add Tierney Cyren To the List

---

README.md

Add Gary Kramlich to the list

---

README.md

I put myself in the middle to hopefully avoid merge conflicts with anyone else contributing at the same time :sweat_smile:

add Kent to the list

---

README.md

Add Sallar Kaboli

---

README.md

Fun Fun Functions is a great YouTube channel for programming (JS and in general)

Add MPJ (Mattias P Johansson) from FunFunFunction

---

README.md

Added HardlyDifficult and RadicalFishGames, two developer streams I regularly watch.
Actually RadicalFishGames is a team of indie game developers, but mainly the developer Felix streams from his computer, while being accompanied by his team members via voice chat.

Added HardlyDifficult and RadicalFishGames

---

README.md

I find Casey's streams are really deeply informative and technical without being too difficult to follow. He explains things really well and knows what he's doing

Adds Casey Muratori

---

README.md

Adds @yupferris to the list of streamers

Add Ferris

---

README.md

adds swizec teller to the list

adds swizec to the list

---

README.md

Adds @simalexan to the list of streamers

Add Alexander Simovic

---

README.md

PR to add Adam13531 as a streamer.

Add Adam13531

---

README.md

Hi there!
I'm finally able to stream after years of wanting to, so I'm starting streaming on JS & OSS projects later this week over on [Twitch](https://twitch.tv/hawkinjs).
Like I said in the md, I plan to stream JS, my journey to learn Rust, Python, and gaming. More to come, but that's all I have planned so far.

Add Josh Hawkins to streamer list

---

README.md

Streams development of a Vectrex emulator in C++ twice a week

Add Antonio Maiorano (daroou2) to the list

---

README.md

Add DrunkDevs

---

README.md

Syanoks is an systems programmer with some very technical but very good streams

Add syanoks

---

README.md

I added all the information about my Twitch channel :+1: 
Awesome initiative folks!

add Joe Bew

---

README.md

CaptainCraft is a C/C++/Rust developer

Add Captainkraft

---

README.md

He's an awesome contributor ! Has many very important projects for the
CL world.
Cheers

add Shinmera: Game Development, Common Lisp

---

README.md

Added my self

---

README.md

Hiya,
I added myself to the list :-)
Cheers,
Keraf

Added Keraf (myself) to the list

---

README.md

Adds @Amorelandra to the list ❤️

Add Amorelandra to README.md

---

README.md

French developper making my own game in C++ and Lua (using my homemade C++ engine)

Add SirLynixVanFrietjes

---

README.md

fixes link to Alexander Simovic full info

fix(link): fixes link to Alexander Simovic info

---

README.md

Add Robin Pokorny

---

README.md

Dev with chill music who has been streaming for the past year.

Add Sebastian Krzyżanowski to the streamer list

---

README.md

Per Vognsen do streaming about creating the software/hardware stack from scratch

Add Per Vognsen

---

README.md

He streams Game Development, Functional Programming, Programming Language Design, Artificial Intelligence, C, C++, Haskell, Rust, Scala
Really recommend.

Add Tsoding

---

README.md

Hey! Thanks for adding me on this list a few weeks ago.
I do use twitter now so I'm adding a link here ^_^

Add SirLynixVanFrietjes Twitter link

---

README.md

Trying this again! Thanks in advance :)

Adding PixelogicDev

---

README.md

Added Eddie Jaoude to list of code streamers

---

README.md

I've added in my Twitch channel with some links. My website is still under development but is relevant, because it's partly what I work on during the stream.
This list has been very helpful to me as a viewer, and I would be honoured to be on it. Thanks!

Adding myself (Jesse Skinner) to README

---

README.md

I haven't written any rust on stream so I'm replacing it with C++ and Elixir, both of which I have projects in the works to revive my stream with :)
While I'm here tho, major props again for maintaining this, Tierney! I'm sure I speak for most folks when I say I really appreciate everything you do for the open source and specifically node communities 🙌

Update Josh Hawkins' info

---

README.md

adds Jeff Lindsay

---

README.md

I've updated my stream details, Twitter account and website.

Update details for Jochen Lillich

---

README.md

I'd like to include my own streaming working to the repository. I run a roughly hour long stream each week to do live development of a Software as a Service project.
The project is implemented in Python using the Django web framework. I cover web development topics including backend, frontend, design, and DevOps work.
Thanks for considering the addition!

Add Matt Layman (Building SaaS with Python and Django)

---

README.md

Add me to README :)

---

README.md

I humbly request my details be added. :)

Add Mark Kraus

---

README.md

People keep telling me I should add myself to this list.
So here we go ¯\_(ツ)_/¯

Add Corbob to the list

---

README.md

Adding Adron Hall.

---

README.md

Added Ninjabunny9000 and WindyBeardGamed. Corrected the alphabetical arrangement of the Developers that stream section as J and K were in the wrong order.

Add Ninjabunny9000 and WindyBeardGames

---

README.md

I am adding myself, I know it's not fantastic, but my stream recommended it yesterday.
I also added an entry for my npx card, I hope that's not too out of the ordinary.

Adding twitch streamer 'roberttables'

---

README.md

And here's another very cool streamer :)

Add Jeff Panici (nybblesio)

---

README.md

Just that - another awesome streamer :)

Add Freya Holmér (Acegikmo)

---

README.md

A few minor updates to HonestDan's entry

HonestDan speaks Welsh sometimes ;) Also webdev, typos

---

README.md

Add Gary Ewan Park to README.md

---

README.md

Added Brandon Satrom (me!) to streamers list

---

README.md

Add David Pedersen to the list

---

README.md

Jon Gjengset is a PhD student at MIT who produces regular Rust streams on Twitch and YouTube.

add Jon Gjengset

---

README.md

Fix typo in ToC link for #andrew-kelley

---

README.md

[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

Adding Bobby Johnson (Auth0Bobby)

---

README.md

Update some of the things I stream

---

README.md

added @ghuntley

---

README.md

I've added myself (ksivamuthu) in twitch streamers list.

Added @ksivamuthu

---

README.md

Adding myself to the list: jitterted on most social media.

Add Ted M. Young to the list

---

README.md

Adding myself to this awesome list! :+1:

Adding - Mark Mandel

---

README.md

Adding Gavin Barron to list

---

README.md

Adding Michael Jolley's stream

---

README.md

Thank you for the opportunity!

Adding DJ Adams to the list

---

README.md

Adding myself to the list :smile:

Add Anton Kuzmenko to the list

---

README.md

I don't know if this is the done thing so feel free to decline if you think someone else should add a streamer rather than the streamer themselves.

Added my stream.

---

README.md

added Matt Groves live coding stream

---

README.md

Go_Maestro_Go is run by Christian Guerin. Christian graduated with an Industrial and Systems Engineering from the University of Florida in 2018. He currently works in Austin, TX, full-time as a Cloud Solution Engineer on the App Development and App Integration Pillars. Before Oracle, he helped co-found SetMine. SetMine was a music app for festival sets and radio mixes with tracklists and events, with a unique approach towards unlocking premium content. In 2013 with his two best friends from high school. They grew to 20K monthly unique users before the team decided to take the app offline in 2017 due to the costs of maintaining the business. Christian competed at UF's Big Idea Competiton four times during his college tenure. He is a hackathon enthusiast, having attended nearly a dozen to …

Adding @Go_Maestro_Go as additional Live streamer

---

README.md

Adding my stream to your list :-)

Added Codebase Alpha

---

README.md

Added Sorskoot to the list

---

README.md

Add Zorchenhimer to the list

---

README.md

Adding @rctatman for her data science streams!
Not sure how to get the link on the top of the readme to link to the name on the bottom...

Add Rachael Tatman rctatman

---

README.md

Daniel Stenberg is the creator of cURL and he occasionally streams updates to the main cURL repo on his twitch channel.
Twitch Channel: https://www.twitch.tv/curlhacker

Added Daniel Stenberg in the list

---

README.md

I can't believe this guy was missing from the list.

Update README.md with new streamer (CodeRushed)

---

README.md

Adding Nick Busey

---

README.md

Adding Andy Li

---

README.md

Added letter headings and horizontal line breaks between sections / capital letters / streamers to break up the expanse of text.

Added some formatting to break up the sections

---

README.md

Added MrStanDu33 (also "known" as Stan Daniels-Roth), a French Web Dev Freelancer and streamer since 2012.

Added MrStanDu33 profile

---

README.md

Added Michael Henderson (with fixed anchor tag link)

Added Michael Henderson (leadcoder / robedcoder)

---

README.md

Fix the anchor tag to jump to CodeRusher (Mark Miller) entry

Fix link to CodeRushed

---

README.md

Fixed Typo in alias, and added alias into main name entry for consistency.

Fixed typo. Also added Alias to main name entry

---

README.md

Some links for looking for generic programming and development categories.

Added a new Twitch category at the end with some development categories 

---

README.md

Added a contents entry to jump to index letter, also added (top) links to go from anywhere in the contents, and after entry entry to jump back to the top.

added achors, and navigation index letters

---

README.md

also added youtube for video archives

updating readme with myself for mainly twitch

---

README.md

Adding the streamer Frank Boucher

Adding Frank Boucher

---

README.md

Adding myself with a multitude of linkage.

Adding Calvin Allen / Coding with Calvin

---

README.md

Benjamin added himself to the end of the B's. I have added him alphabetically.

Put Benjamin in his place

---

README.md

Added Liz Phillips (Illuminated Space)

---

README.md

Added streamer Dillon Pentz who works on OBS coding. Found him following a raid, and he was working on screen reader accessibility for OBS

Added Dillon Pentz

---

README.md

Added IAmFletcher

---

README.md

Added Codephobia

---

README.md

Adding Cailir to list, pt-br streamer

Added Cailir

---

README.md

Adding Albérico Dias Barreto Filho to list, pt-br streamer

Added Albérico Dias Barreto Filho

---

README.md

Added Skillvid

---

README.md

Added Masood Sadri

---

README.md

New streamer I stumbled across on Twitch.

add KalleHallden

---

README.md

Fix on hyperlink to leomendesm

Fix on hyperlink to leomendesm

---

README.md

Added HowToCodeWell

---

README.md

Also part of the `LiveCoders` team on Twitch.  
I stream _regularly_ (usually once every week, usually on Sunday afternoon (CET)).

Added Sch3lpSC2

---

README.md

[He told me too](https://twitter.com/_wissamyoussef/status/1188865130882314241)

feat(one-more-time): were going to readmeate

---

README.md

Hello,
Baggers is a well known Lisp hacker making super useful tutorials and cool projects of coding with OpenGL or the GPU, for games.
He still streams nearly every week.
Cheers

add Baggers, streaming Graphics Programming, Common Lisp tutorials

---

README.md

I'd like to add myself to your list. I live-code working on [this app](https://github.com/ChaelCodes/HuntersKeeper) every Sunday.
This PR description is the shortest I've ever written.
Thanks.

Add ChaelCodes to awesome-developer-streams

---

README.md

Description of Changes
---
I'd like to add my twitch stream to your list. I stream Haskell and Elm Tuesdays and Thursdays. Thanks for your time!

Add twitch streamer Chiroptical

---

README.md

Adding myself to the list of streamers from twitch. 
preferred social media https://twitter.com/Mark0x1

Adding Marko Pavlovic to the list of streamers

---

README.md

This PR adds Tae'lur Alexis' stream

Add Tae'lur Alexis

---

README.md

Add Java Streamer Nicolai Parlog (nipafx)

Add Nicolai Parlog

---

README.md

Add Brian Lagunas

---

README.md

Adds the following streamers and their tech stacks of choice from Twilio:
- Brent Schooley
- Corey Weathers
- Gary Hockin
- Layla Porter

Adds Twilio Streamers to the list

---

README.md

Thought I'd add myself. Up to you if you think I'm awesome...

Add Phil Nash

---

README.md

Added Josh Kupka

---

README.md

added Beachcasts

---

README.md

- now streaming on YouTube
- also updated list of topics

update 'dj-adams' entry

---

README.md

I moved from Twitch to YouTube

Updated Eddie Jaoude

---

README.md

Adding myself to the list of streamers!
Twitter: @darkosubotica

Adding Darko Meszaros

---

README.md

Added Jorge Cano to the list of streamers !

Added Jorge Cano

---

README.md

hey there, I'm adding myself heheh ✨⚡️

Add Jonatas "Jojo" Baldin

---

README.md

April Speight, Vogue and Code added

Added Vogue and Code (April Speight)

---

README.md

My links were from back when I worked on Bot Land. I wanted to update them now that I've shifted my show to Adam Learns.
Thanks for maintaining this repository!

Update links for Adam13531

---

README.md

Added Lucas Montano to the list of streamers

Added Lucas Montano

---

README.md

I'm the eponymous Jeff, software engineer at Slack and alumnus of game studios WayForward and Zindagi. My friend Dom and I have a pair programming stream where we're building a game from scratch, and teaching each other how to do it in the process. We hope this is a good contribution to your list. Thank you!

new stream: Jeff and Dom Make a Game

---

README.md

Adding the stream and details for Joseph Guadagno

Adding new Stream for Joseph Guadagno

---

README.md

Add Brent Ozar. SQL Server dude.

Add brent ozar

---

README.md

Fix Gary Kramlich's YouTube

---

README.md

twitch.tv/MattIPv4
twitter.com/MattIPv4
github.com/MattIPv4
mattcowley.co.uk

Add Matt Cowley

---

README.md

Update links, etc., for JitterTed (that's me!).

Fix up JitterTed

---

README.md

Adding myself. Thanks for creating this index! 💫

Added Eralp Karaduman

---

README.md

Thanks for having such a great list! Let me represent the first U.

Adding Clark Sell's ( UnspecifiedSoftware ) live stream

---

README.md

Angie Jones is a Senior Developer Advocate who specializes in test automation strategies and techniques.
https://angiejones.tech

Added Java Developer Expert "Angie Jones" Streaming Details

---

README.md

* Remove discord link
* Edit description

Btor: Remove discord / Edit description

---

README.md

I have started streaming on twitch 🥳

Add C0d3Spaghetti

---

README.md

**Preferred social media:** [Alemayhu's server](https://discord.gg/PSKC3uS) on Discord

Add Alemayhu to the awesome-developer-streams

---

README.md

No `OCaml` streamers.
Start streaming OCaml, and self-add :)

feat: add chris dieringer

---

README.md

I'm Dylan. I'm a coder, speaker, and the creator of the Rockstar programming language, and I stream various nerdy things on Twitch, from live coding C# and .NET to performing nerd music comedy shows. Cool project; I'd like to be on your list, please!

Add Dylan Beattie's stream and website links

---

README.md

Binary Solo does game development. Mostly a C++ stream, occasionally guest art / music.

Adding Binary Solo

---

README.md

Added myself lol, just saw this project under the "Twitch" tag on GitHub and wanted to add myself :)

➕ Added "mmatt".

---

README.md

Thanks for continuing to maintain this list!

update DJ Adams description

---

README.md

Added my links and stream info because the world needs to know.

Adding bdougie to the list of streamers

---

README.md

This is on behalf of whitep4nth3r and she is aware I'm doing it for her (chatted about it in https://www.twitch.tv/videos/978567971). Thanks!

add whitep4nth3r

---

README.md

My Twitch name recently changed from ChefBrent to HeccBrent. I've made the appropriate changes to README.md.

Updated Brent Schooley due to name change from ChefBrent to HeccBrent

---

README.md

Remove Marco Bruno

---

README.md

Changed my username again, sorry about that! lol

Updated my Twitch link.

---

README.md

french streamer for Delphi / Pascal and web technologies

add Patrick Prémartin

---

README.md

Add tek256 to list

---

README.md

Adding myself (mattytwoshoes) to the list, if that's permitted :)
Thank you for maintaining this project!

adding myself to this list

---

README.md

Added Jason Thor Hall (Pirate Software)

Added Thor

---

README.md

Replaces outdated links for PirateSoftware with new ones, also fixes a typo

PirateSoftware - Replace outdated links

---

README.md

Adds [Kris Nova](https://www.twitch.tv/krisnova/about) stream

Add Kris Nova

---

README.md

I've switched from Twitch to a self-hosted Owncast instance, and from Twitter to Mastodon.

Jochen Lillich: URL updates

---

README.md

Added teej_dev
Actively working on Neovim, creating it's plugin, making it easy for beginner to jump into this awesome nvim editor.

Added teej_dev

---

README.md

He makes various rust-related videos.

Add Amos (fasterthanlime)

---

README.md

Adding Laur Spilca an experienced java backend developer especially on spring framework and he is an author of four books: Troubleshooting Java, Protecting User Data with Spring Security and OAuth2, Spring Security in Action and Spring Start Here. He has very useful live streams on youtube about java and spring framework.
https://www.youtube.com/@laurspilca/streams
https://laurspilca.com/books/

Adding Laur Spilca a senior java backend developer streamer

---

README.md

Adam13531 changed his twitch handle when he recently started streaming again.

fix: AdamsLearnsLive: name change

---

README.md

feat: add andrew courter

---

README.md

I am adding myself to this list. I am happy to make any edits or changes as necessary.

Add cmgriffing to the list

---

README.md

i stream on twitch! i saw cmgriffing adding himself, so I opened this PR too :)
i also fixed some consistency issues i noticed.

add badcop + fix some typos

---

README.md

Add mafik to the list
